In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0


## Intro to Tensors

In [31]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [32]:
scalar.ndim

0

In [33]:
scalar.item()

7

In [34]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [35]:
vector.ndim

1

In [36]:
vector.shape

torch.Size([2])

In [37]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [38]:
MATRIX.ndim

2

In [39]:
MATRIX[1]

tensor([ 9, 10])

In [40]:
MATRIX.shape

torch.Size([2, 2])

In [41]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [42]:
TENSOR.ndim

3

In [43]:
TENSOR.shape

torch.Size([1, 3, 3])

In [44]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensors

In [48]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4720, 0.6534, 0.5153, 0.6619],
        [0.4422, 0.2018, 0.3886, 0.7476],
        [0.4030, 0.2480, 0.3422, 0.7023]])

In [49]:
random_tensor.ndim

2

In [52]:
random_image_size_tensor = torch.rand(225, 225, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([225, 225, 3]), 3)

## Zeros and ones

In [53]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [55]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors

In [62]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [2]:
float_32_tensor = torch.tensor([3.0, 10.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [3]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [4]:
multiply = float_16_tensor * float_32_tensor
multiply, multiply.dtype

(tensor([  9., 100.]), torch.float32)

## Getting info from tensors

In [5]:
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([2]), device(type='cpu'))

## Manipulating tensors - tensor operations

In [9]:
tensor = torch.tensor([1, 2, 3, 4])
tensor + 10

tensor([11, 12, 13, 14])

In [10]:
tensor * 10

tensor([10, 20, 30, 40])

In [11]:
tensor - 10

tensor([-9, -8, -7, -6])

In [12]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [14]:
tensor_2 = torch.tensor([1, 2])

In [18]:
torch.add(tensor, tensor_2)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

## Matrix multiplication

In [23]:
# Element wise
tensor = torch.tensor([1, 2, 3])
print(tensor)
tensor * tensor

tensor([1, 2, 3])


tensor([1, 4, 9])

In [25]:
# Dot product
torch.matmul(tensor, tensor)

tensor(14)

In [26]:
tensor

tensor([1, 2, 3])

In [27]:
1*1 + 2*2 + 3*3

14

In [40]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 830 μs, sys: 841 μs, total: 1.67 ms
Wall time: 924 μs


In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 109 μs, sys: 28 μs, total: 137 μs
Wall time: 124 μs


tensor(14)

In [42]:
%%time
np.dot(tensor, tensor)

CPU times: user 151 μs, sys: 23 μs, total: 174 μs
Wall time: 162 μs


<timed eval>:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword


np.int64(14)

In [43]:
%%time
tensor @ tensor

CPU times: user 114 μs, sys: 39 μs, total: 153 μs
Wall time: 144 μs


tensor(14)

In [44]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) 

tensor([[1.0495, 0.7713, 0.8399],
        [0.3915, 0.0977, 0.3739],
        [0.7009, 0.3610, 0.6100]])

In [46]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)) 

tensor([[0.9064, 0.4017],
        [1.0050, 0.8130]])

In [49]:
torch.matmul(torch.rand(3, 3), torch.rand(3, 3)) 

tensor([[1.1299, 1.1038, 1.0809],
        [1.4506, 1.3366, 1.4295],
        [1.0883, 0.6203, 1.1290]])

In [50]:
torch.matmul(torch.rand(7, 10), torch.rand(10, 10)) 

tensor([[3.1477, 2.4358, 2.7631, 3.1966, 3.2021, 2.3345, 2.4333, 1.8012, 3.3844,
         2.7214],
        [3.3746, 2.2939, 2.9313, 3.4438, 3.2687, 3.0711, 2.7665, 2.1255, 3.8864,
         3.4424],
        [1.6323, 0.9999, 1.3854, 1.8268, 1.4021, 1.8839, 1.4148, 1.4887, 2.1049,
         2.0074],
        [2.9099, 2.2665, 2.9456, 3.2853, 2.7814, 1.9818, 1.9402, 1.5102, 2.8916,
         2.4793],
        [2.2377, 1.7841, 2.5278, 2.9658, 2.6455, 2.3651, 2.1781, 1.4261, 2.6949,
         2.6669],
        [3.8209, 1.9737, 3.5906, 3.4319, 3.3718, 3.3001, 3.0318, 1.8275, 3.9235,
         3.9269],
        [2.5569, 1.2923, 2.2078, 2.0002, 2.2013, 1.8791, 1.8634, 0.9671, 2.4082,
         2.5562]])

## Dealing with shape errors

In [51]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

In [54]:
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [55]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])