In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Intro to Tensors

In [31]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [32]:
scalar.ndim

0

In [33]:
scalar.item()

7

In [34]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [35]:
vector.ndim

1

In [36]:
vector.shape

torch.Size([2])

In [37]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [38]:
MATRIX.ndim

2

In [39]:
MATRIX[1]

tensor([ 9, 10])

In [40]:
MATRIX.shape

torch.Size([2, 2])

In [41]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [42]:
TENSOR.ndim

3

In [43]:
TENSOR.shape

torch.Size([1, 3, 3])

In [44]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensors

In [48]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4720, 0.6534, 0.5153, 0.6619],
        [0.4422, 0.2018, 0.3886, 0.7476],
        [0.4030, 0.2480, 0.3422, 0.7023]])

In [49]:
random_tensor.ndim

2

In [52]:
random_image_size_tensor = torch.rand(225, 225, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([225, 225, 3]), 3)

## Zeros and ones

In [53]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [55]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors

In [62]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [2]:
float_32_tensor = torch.tensor([3.0, 10.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [3]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [4]:
multiply = float_16_tensor * float_32_tensor
multiply, multiply.dtype

(tensor([  9., 100.]), torch.float32)

## Getting info from tensors

In [5]:
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([2]), device(type='cpu'))

## Manipulating tensors - tensor operations

In [9]:
tensor = torch.tensor([1, 2, 3, 4])
tensor + 10

tensor([11, 12, 13, 14])

In [10]:
tensor * 10

tensor([10, 20, 30, 40])

In [11]:
tensor - 10

tensor([-9, -8, -7, -6])

In [12]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [14]:
tensor_2 = torch.tensor([1, 2])

In [18]:
torch.add(tensor, tensor_2)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

## Matrix multiplication

In [23]:
# Element wise
tensor = torch.tensor([1, 2, 3])
print(tensor)
tensor * tensor

tensor([1, 2, 3])


tensor([1, 4, 9])

In [25]:
# Dot product
torch.matmul(tensor, tensor)

tensor(14)

In [26]:
tensor

tensor([1, 2, 3])

In [27]:
1*1 + 2*2 + 3*3

14

In [40]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 830 μs, sys: 841 μs, total: 1.67 ms
Wall time: 924 μs


In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 109 μs, sys: 28 μs, total: 137 μs
Wall time: 124 μs


tensor(14)

In [42]:
%%time
np.dot(tensor, tensor)

CPU times: user 151 μs, sys: 23 μs, total: 174 μs
Wall time: 162 μs


<timed eval>:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword


np.int64(14)

In [43]:
%%time
tensor @ tensor

CPU times: user 114 μs, sys: 39 μs, total: 153 μs
Wall time: 144 μs


tensor(14)

In [44]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) 

tensor([[1.0495, 0.7713, 0.8399],
        [0.3915, 0.0977, 0.3739],
        [0.7009, 0.3610, 0.6100]])

In [46]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)) 

tensor([[0.9064, 0.4017],
        [1.0050, 0.8130]])

In [49]:
torch.matmul(torch.rand(3, 3), torch.rand(3, 3)) 

tensor([[1.1299, 1.1038, 1.0809],
        [1.4506, 1.3366, 1.4295],
        [1.0883, 0.6203, 1.1290]])

In [50]:
torch.matmul(torch.rand(7, 10), torch.rand(10, 10)) 

tensor([[3.1477, 2.4358, 2.7631, 3.1966, 3.2021, 2.3345, 2.4333, 1.8012, 3.3844,
         2.7214],
        [3.3746, 2.2939, 2.9313, 3.4438, 3.2687, 3.0711, 2.7665, 2.1255, 3.8864,
         3.4424],
        [1.6323, 0.9999, 1.3854, 1.8268, 1.4021, 1.8839, 1.4148, 1.4887, 2.1049,
         2.0074],
        [2.9099, 2.2665, 2.9456, 3.2853, 2.7814, 1.9818, 1.9402, 1.5102, 2.8916,
         2.4793],
        [2.2377, 1.7841, 2.5278, 2.9658, 2.6455, 2.3651, 2.1781, 1.4261, 2.6949,
         2.6669],
        [3.8209, 1.9737, 3.5906, 3.4319, 3.3718, 3.3001, 3.0318, 1.8275, 3.9235,
         3.9269],
        [2.5569, 1.2923, 2.2078, 2.0002, 2.2013, 1.8791, 1.8634, 0.9671, 2.4082,
         2.5562]])

## Dealing with shape errors

In [51]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

In [54]:
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [55]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Tensor aggregation - min, max, mean, sum, etc.

In [2]:
x = torch.arange(0, 100, 1)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [14]:
torch.max(x), x.max()

(tensor(99), tensor(99))

In [25]:
# works only with float
torch.mean(x.type(torch.float16))

tensor(49.5000, dtype=torch.float16)

In [21]:
torch.sum(x), x.sum()

(tensor(4950), tensor(4950))

In [22]:
torch.median(x), x.median()

(tensor(49), tensor(49))

## Finding positional min and max

In [30]:
x = torch.tensor([1, 2, 3, -1])

In [31]:
# find the position where the minimum is
x.argmin()

tensor(3)

In [33]:
x[3]

tensor(-1)

In [37]:
# find the position where the maximum is
x.argmax()

tensor(2)

In [38]:
x[2]

tensor(3)

## Reshaping, viewing and stacking
* **Reshape** - reshapes an input tensor to a desired shape
* **View** - Return a view of an input tensorof certain shape but keep the same memory as the orginal
* **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze** - remove all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [49]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [52]:
# Reshape
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [57]:
# View - changing a view `z` changes the tensor `x` (because a view of a tensor shares the same memory as the original tensor)
z = x.view(5, 2)
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [58]:
z[:, 0] = 5
print(z)
print(x)

tensor([[ 5.,  2.],
        [ 5.,  4.],
        [ 5.,  6.],
        [ 5.,  8.],
        [ 5., 10.]])
tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.])


In [59]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])

In [60]:
x_stacked.shape

torch.Size([4, 10])

In [61]:
x_hstacked = torch.stack([x, x, x, x], dim=1)
x_hstacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 5.,  5.,  5.,  5.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  8.,  8.,  8.],
        [ 5.,  5.,  5.,  5.],
        [10., 10., 10., 10.]])

In [62]:
x_hstacked.shape

torch.Size([10, 4])

In [68]:
# Squeezing
y = x.reshape(1, 10)
print(y.shape)
y_squeezed = y.squeeze()
print(y_squeezed.shape)

torch.Size([1, 10])
torch.Size([10])


In [71]:
# Unsqueezing
print(y_squeezed.shape)
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(y_unsqueezed.shape)

torch.Size([10])
torch.Size([1, 10])


In [95]:
# Permute - rearanges the dimensions of a traget tensor in a specified order
x = torch.rand(3, 2, 5)
print(x.shape)
x_permuted = x.permute(2, 0, 1) # these are indecies, so the last -> first, the first -> second, the second -> last
print(x_permuted.shape)

torch.Size([3, 2, 5])
torch.Size([5, 3, 2])


In [96]:
x[0]

tensor([[0.6086, 0.3110, 0.1212, 0.3728, 0.5118],
        [0.9343, 0.5218, 0.6457, 0.1189, 0.3732]])

In [97]:
x_permuted[:, :, 0][0] = 3.9

In [98]:
x[0]

tensor([[3.9000, 0.3110, 0.1212, 0.3728, 0.5118],
        [0.9343, 0.5218, 0.6457, 0.1189, 0.3732]])