In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0


## Intro to Tensors

In [31]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [32]:
scalar.ndim

0

In [33]:
scalar.item()

7

In [34]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [35]:
vector.ndim

1

In [36]:
vector.shape

torch.Size([2])

In [37]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [38]:
MATRIX.ndim

2

In [39]:
MATRIX[1]

tensor([ 9, 10])

In [40]:
MATRIX.shape

torch.Size([2, 2])

In [41]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [42]:
TENSOR.ndim

3

In [43]:
TENSOR.shape

torch.Size([1, 3, 3])

In [44]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensors

In [48]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4720, 0.6534, 0.5153, 0.6619],
        [0.4422, 0.2018, 0.3886, 0.7476],
        [0.4030, 0.2480, 0.3422, 0.7023]])

In [49]:
random_tensor.ndim

2

In [52]:
random_image_size_tensor = torch.rand(225, 225, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([225, 225, 3]), 3)

## Zeros and ones

In [53]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
zeros * torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [55]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors

In [62]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [67]:
float_32_tensor = torch.tensor([3.0, 10.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [68]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [71]:
multiply = float_16_tensor * float_32_tensor
multiply, multiply.dtype

(tensor([  9., 100.]), torch.float32)